### ISSUE TITLE
validatedAddress response inconsistent to order request properties

### ISSUE THREAD

**Issue by henry-all3dp** [ceo-treatstock/apiv2#1]
The order request has been recently updated to contain `first_name` and `last_name` property for the shipping address. But the validatedAddress response for a failed order request still contains the concatenated `contact_name`.

Problem: This looks like an inconsistency in the API. It also leads to problems when the order request is replaced with the updated address provided in the validatedAddress response as the `contact_name` field cannot be used for the new order request.

Proposal: The validatedAddress response contains `first_name` and `last_name` properties similar to the order request.

**Comment by ceo-treatstock** [comment]
Thank you for comment. We will fix it.

**Comment by alex-all3dp** [comment]
Apparently the `validatedAddress` response format has been changed to
```
{
        country: { type: 'string' },
        state: { type: 'string' },
        city: { type: 'string' },
        street: { type: 'string' },
        street2: { type: 'string' },
        zip: { type: 'string' }
}
```
without any notification or documentation update.

Please confirm that this is the case. If yes, the issue can be closed because the name properties are not part of the response anymore

**Comment by ceo-treatstock** [comment]
Response format may be changed. All changes can be monitored by RSS feed: https://github.com/ceo-treatstock.atom
Example commit with comment: add Validated Address model
As you can see, all those fields has string type now: https://github.com/ceo-treatstock/apiv2/blob/master/models/ValidatedAddress.php
