### ISSUE TITLE
Endpoint /printable-pack-costs does not support materials

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#10]
As documented in https://github.com/Treatstock/apiv2#additional-features it is possible to pick particular materials from a material group when configuring a printable pack for placing an order.

For price comparison purposes it would be necessary to reflect the different materials and their respective prices in the response of `/printable-pack-costs` as well. Rather than only listing prices per `materialGroup`, it should include a price for each available `material` + `color` combination.

Suggested response payload:

```json
[
  {
    "printablePackId": 544795,
    "materialGroup": "Polyester",
    "material": "PETG",
    "printer": "...",
    "providerId": 1,
    "rating": 5,
    "reviewsCount": 56,
    "color": "Blue",
    "price": 6.99,
    "deliveryPrice": 7.27,
    "url": "..."
  },
  {
    "printablePackId": 544795,
    "materialGroup": "Polyester",
    "material": "HIPS",
    "printer": "...",
    "providerId": 1,
    "rating": 5,
    "reviewsCount": 29,
    "color": "Red",
    "price": 5.49,
    "deliveryPrice": 4.02,
    "url": "..."
  }
]
```

**Comment by alex-all3dp** [comment]
@ceo-treatstock @analitic1983 any feedback on this? Is this possible to implement on your end?

**Comment by ceo-treatstock** [comment]
@alex-all3dp sorry for the late reply. Please use the request 'ChangePrintablePackRequest', you'll be able to choose material

**Comment by alex-all3dp** [comment]
@ceo-treatstock I know that we are able to configure a printable pack for a particular material. This issue is about the need for us to being able to differentiate the materials inside each material group when fetching printable pack offers, so BEFORE we actually configure a printable pack. Would it be possible for you to adapt the response format for `/printable-pack-costs` as suggested in this post and include prices for all materials of each material group in the response?

**Comment by ceo-treatstock** [comment]
@alex-all3dp unfortunately, we aren't ready to provide prices for each option of material, color & infill in one inquiry since it leads to heavy traffic, as we will be needed to respond for 60,000 options. This is a huge amount of data. We offer to use different queries to confirm the prices for certain material or infill.

**Comment by alex-all3dp** [comment]
@ceo-treatstock I looked into this again and understand your issue here. The queries you mention would be an option on our end. But how is it possible to query/filter for only a certain material or infill on the `/printable-pack-costs` endpoint? Do you support query parameters like `?material=ASA` , which are not mentioned in the docs?
