### ISSUE TITLE
Enhancement: /printable-pack-costs lists infill prices

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#11]
It would greatly simplify price fetching for different infill levels if it were not required to first change the infill level for a particular materialGroup in the printable pack but instead if the price response always lists all prices for the different levels.

Suggested price response:

```json
[
 {
    "printablePackId": 544795,
    "materialGroup": "Polyester",
    "printer": "...",
    "providerId": 1,
    "rating": 5,
    "reviewsCount": 29,
    "color": "Red",
    "price": 5.49,
    "deliveryPrice": 4.02,
    "url": "...",
    "infills": {
        "20": { "price": 5.49 },
        "25": { "price": 6.10 },
        "30": { "price": 6.88 },
        ...
        "100": { "price": 11.11 }
    }
  }
```

The `price` would still reflect the price for the configured infill level, but additionally the `infill` array allows price comparisons across all infill levels for that material+color combination.

**Comment by alex-all3dp** [comment]
@ceo-treatstock @analitic1983 any feedback on this? Is this possible to implement on your end?

**Comment by ceo-treatstock** [comment]
@alex-all3dp sorry for the late reply. To get the prices for different percentage of infill please use the request 'ChangePrintablePackRequest'

**Comment by alex-all3dp** [comment]
@ceo-treatstock as stated previously we know this is possible but on our end it would be rather complicated to aggregate multiple infill prices if we have to reconfigure the printable packs for every different infill price we want to fetch. Hence the question if it would be possible to adapt the `/printable-pack-costs` response as suggested in this ticket

**Comment by ceo-treatstock** [comment]
@alex-all3dp Unfortunately, we aren't ready to provide prices for each option of material, color & infill in one inquiry since it leads to heavy traffic, as we will be needed to respond for 60,000 options. This is a huge amount of data. We offer to use different queries to confirm the prices for certain material or infill.
