### ISSUE TITLE
Call to a member function getAmount() on null

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#12]
Hello,

we are seeing some 500 errors on our end for the `/printable-pack-costs` API with the error message `Call to a member function getAmount() on null`.

Example request: https://www.treatstock.com/api/v2/printable-pack-costs?private-key=54839e05e75bff1&printablePackId=1229558&location%255Bcountry%255D=SG

**Comment by ceo-treatstock** [comment]
Apologies for the late reply. The error was fixed.
