### ISSUE TITLE
Request for fetching order status

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#2]
Hello,
it would be great if you API would offer a route for fetching the order status, e.g. "in production", "dispatched", etc.

Suggestion:

Route: 
`GET /order-status?orderId=<orderId>` 
or 
`GET /order-status/<orderId>`

Response:
```
{
  "order": "<placed | in production | dispatched | ... >",
  "payment": "<waiting for payment | paid ...>"
}

**Comment by ceo-treatstock** [comment]
Thank you for issue. We will publish this functional tommorow.

**Comment by alex-all3dp** [comment]
Nice, thank you! :)

**Comment by ceo-treatstock** [comment]
Example:
https://github.com/ceo-treatstock/apiv2/blob/master/examples/05_PlaceOrder.php
Code: $orderStatusRequest = ...

**Comment by alex-all3dp** [comment]
Thank you for the quick implementation!

Could you provide additional documentation for the different values for `orderState`, `paymentState` and `attemptState` ?

In our workbench I see orders that are "in production" having different values for `attemptState`, e.g. "printing" and "accepted". Similarly there are "paid" orders with different `paymentState` values.

Could you document which values there are and their respective meaning? Ideally how they correspond to what is seen in the workbench.

Thank you!

**Comment by ceo-treatstock** [comment]
Hi. We have described base statuses: https://github.com/ceo-treatstock/apiv2/blob/master/models/responses/OrderStatusResponse.php

**Comment by alex-all3dp** [comment]
Thank you! :)
