### ISSUE TITLE
ASA not provided as material via API

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#4]
According to our last email conversation with Anzhelika Khasanova, ASA should be available as a material group via the API.

But neither https://www.treatstock.com/api/v2/material-group-colors nor a price request via https://www.treatstock.com/api/v2/printable-pack-costs?printablePackId=
include ASA in their response

**Comment by analytic83** [comment]
ASA material included in "High-Performance Plastics" group. Please search it in costs answer.

**Comment by alex-all3dp** [comment]
I found the material group you mentioned. Does it include any other materials besides ASA or can we safely present it as "ASA"?

**Comment by analytic83** [comment]
Yes, you can.

**Comment by alex-all3dp** [comment]
Works, thank you!
