### ISSUE TITLE
Provide tracking information for shipped orders

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#5]
It would be great if the new order status request https://www.treatstock.com/api/v2/place-order/state would include tracking information for orders that have been shipped already.

Maybe the response could include a new object for that purpose?

```javascript
{
  "success": true,
  "orderId": xxx,
  "total": "xxx",
  "url": "https://www.treatstock.com/workbench/order/view/...",
  "orderState": "processing",
  "paymentState": "settled",
  "attemptState": "sent",
  "shipping": {
     "carrier": <carrierName>,
     "trackingNumber": <trackingNumber>
}
```

The field could be `null` for orders that have not been sent yet (or left out entirely, whatever suits you best :) )

**Comment by analytic83** [comment]
Thank you, we will add this fields next week.

**Comment by analytic83** [comment]
Merged into release.
