### ISSUE TITLE
Allow scaling of model via API

### ISSUE THREAD

**Issue by henry-all3dp** [ceo-treatstock/apiv2#6]
Currently, models of a printable pack can be scaled using a scale unit, e.g.:
`curl -X PUT -d scaleUnit=mm https://www.treatstock.com/api/v2/printable-packs/<id>?private-key=<api-token>`

It would be great to additionally support a free scaling factor for the model dimensions (length, width, height) similar to the linear scale option in the treatstock client via the API:
<img width="986" alt="grafik" src="https://user-images.githubusercontent.com/31536819/69148326-54300880-0ad4-11ea-9ad8-67487f75ba8c.png">

Proposed API route:
`PUT /printable-packs/<printable-pack-id>` (re-using existing update route)
Proposed payload:
```
{
  ...,
  "scale": {
    "MP:<id>": 1.25
  }
}
```

Proposed change to response payload of `GET /printable-packs/<printable-pack-id>`:
```
{
  "id": <printable-pack-id>,
  ...
  "parts": {
    "MP:<id>": {
      "uid": "MP:<id>",
      "name": "filename",
      "qty": 1,
      "hash": "hash",
      "scale": 2, <-- new
      "size": {
        "length": 40, <-- value with applied scale
        "width": 40, <-- value with applied scale
        "height": 40, <-- value with applied scale
        "measure": "mm"
      },
      "originalSize": {
        "length": 20,
        "width": 20,
        "height": 20,
        "measure": "mm"
      },
      "weight": 5,
      "texture": {
        "color": "White",
        "materialGroup": "PLA"
      }
    }
  }
}
```

**Comment by analytic83** [comment]
Well, we will add this feature this month.

**Comment by analytic83** [comment]
Pushed in master

**Comment by alex-all3dp** [comment]
Hello @analitic1983,

we just looked into integrating the scaling feature via your API.

it appears that you do not support scaling different model parts inside a printable pack independently of each other.

Would it be feasible for you to implement the feature it was proposed originally by @henry-all3dp with a request payload similar to changing quantities indepdendently?

```
{
  ...,
  "scale": {
    "MP:<id>": 1.25,
    "MP:<id2>": 2,
     ...
  }
}
```

Best regards

**Comment by analytic83** [comment]
Hello, alex-all3dp 

We don’t support scaling for independent parts at all. This feature isn’t present on our website, too. The main reason is that usually, parts in one pack require the same scale and a different scaling can cause mistakes.
