### ISSUE TITLE
API support for .obj models appears to be broken

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#7]
Hello,

when we upload .obj models to your service via the API, we are unable to get prices for the printable pack that is being created. 

Steps to reproduce: 

1) Upload .obj model via `POST https://www.treatstock.com/api/v2/printable-packs`

2) Retrieve printable pack information via `GET https://www.treatstock.com/api/v2/printable-packs/408690`. The response for all .obj models looks similar to
```
{
  "id": 408690,
  "model3d_id": 3586169,
  "created_at": "2020-01-10 12:09:14",
  "affiliate_price": "0.0000",
  "affiliate_currency": "USD",
  "calculated_min_cost": "not_calculated_yet",
  "success": true,
  "scaleUnit": "mm",
  "largestPartSize": null,
  "parts": {
    "MP:3425674": {
      "uid": "MP:3425674",
      "name": "resall.stl",
      "qty": 1,
      "hash": "c61b4a855f4c4619e0cc41a3e4d127b2",
      "size": null,
      "originalSize": null,
      "weight": 0,
      "texture": {
        "color": "White",
        "materialGroup": "PLA"
      }
    }
  }
}
```
where the part `name` is always `resall.stl` and the `calculated_min_cost` is `not_calculated_yet`

3) Try to fetch prices via `GET https://www.treatstock.com/api/v2/printable-pack-costs?printablePackId=408690&location[country]=US`. Response is always
```
{
  "success": false,
  "reason": "not_calculated_yet"
}
```

Oddly enough, if we follow the `redir` URL that is part of the initial upload response, e.g. "https://www.treatstock.com/catalog/model3d/preload-printable-pack?packPublicToken=8c330aa-7bc6a45-4baa2fe", the .obj file is correctly displayed in the workbench and prices are being fetched.

After we followed the URL, price retrieval via the API also works.
Fetching the printable pack info now also includes the dimensions, but still the wrong file name:
```
{
  "id": 408690,
  "model3d_id": 3586169,
  "created_at": "2020-01-10 12:09:14",
  "affiliate_price": "0.0000",
  "affiliate_currency": "USD",
  "calculated_min_cost": {
    "materialGroup": "PLA",
    "color": "White",
    "cost": 4.99
  },
  "success": true,
  "scaleUnit": "mm",
  "largestPartSize": {
    "length": 16,
    "width": 16,
    "height": 1.502,
    "measure": "mm"
  },
  "parts": {
    "MP:3425674": {
      "uid": "MP:3425674",
      "name": "resall.stl",
      "qty": 1,
      "hash": "c61b4a855f4c4619e0cc41a3e4d127b2",
      "size": {
        "length": 16,
        "width": 16,
        "height": 1.502,
        "measure": "mm"
      },
      "originalSize": {
        "length": 16,
        "width": 16,
        "height": 1.502,
        "measure": "mm"
      },
      "weight": 1.25,
      "texture": {
        "color": "White",
        "materialGroup": "PLA"
      }
    }
  }
}
```

**Comment by alex-all3dp** [comment]
Hello,

we received feedback from your end, that the API has been fixed. I did some testing and unfortunately it is still not usable for .obj files.

Here are my findings so far:

- Uploading a .zip file with an embedded .obj still results in the same error behaviour described above
- Uploading a .obj file now results in a printable pack for which prices can be fetched but it still appears to be invalid for the following reasons:
-- The name of the part is still `resall.stl` which makes it impossible to map the part to its original model file based on file name
-- The part id received in the original upload response is one count below the part id in the `GET /printable-packs/:id` response.

Example response from POST:

``` 
{
  "success": true,
  "id": 422749,
  "redir": "https://www.treatstock.com/catalog/model3d/preload-printable-pack?packPublicToken=13f6f5f-58c30d1-1a8b887",
  "widgetUrl": "https://www.treatstock.com/api/v2/printable-pack-widget/?apiPrintablePackToken=13f6f5f-58c30d1-1a8b887",
  "widgetHtml": "<!-- ApiWidget: 13f6f5f-58c30d1-1a8b887 --><link href='https://www.treatstock.com/css/embed-user.css' rel='stylesheet' /><iframe class='ts-embed-userwidget' src='https://www.treatstock.com/api/v2/printable-pack-widget/?apiPrintablePackToken=13f6f5f-58c30d1-1a8b887' frameborder='0'></iframe>",
  "parts": {
    "MP:3601736": {
      "uid": "MP:3601736",
      "name": "Shield_transformed.obj",
      "qty": 1,
      "hash": "e724a8d86a1932a2950433de9d1dcd1b"
    }
  }
}
```

Response from `GET /printable-packs/422749`

```
{
  "id": 422749,
  "model3d_id": 3648246,
  "created_at": "2020-01-21 08:31:26",
  "affiliate_price": "0.0000",
  "affiliate_currency": "USD",
  "calculated_min_cost": "client_location_not_set",
  "success": true,
  "scaleUnit": "mm",
  "largestPartSize": {
    "length": 15.8,
    "width": 15.8,
    "height": 1.483,
    "measure": "mm"
  },
  "parts": {
    "MP:3601737": {
      "uid": "MP:3601737",
      "name": "resall.stl",
      "qty": 1,
      "hash": "49f72d0967c9effb0cbe7f107261a6ca",
      "size": {
        "length": 15.8,
        "width": 15.8,
        "height": 1.483,
        "measure": "mm"
      },
      "originalSize": {
        "length": 15.8,
        "width": 15.8,
        "height": 1.483,
        "measure": "mm"
      },
      "weight": 1.25,
      "texture": {
        "color": "White",
        "materialGroup": "PLA"
      }
    }
  }
}
```

Hope you can help us out by fixing these issues soon. Thank you! :)

**Comment by alex-all3dp** [comment]
@ceo-treatstock any updates on this?

**Comment by analytic83** [comment]
Sorry for waiting, obj files may contain several stl models. Because this we return common resall name for model, and other files for other parts.
