### ISSUE TITLE
Support infills for price fetching

### ISSUE THREAD

**Issue by alex-all3dp** [ceo-treatstock/apiv2#8]
Currently it does not seem possible to retrieve correct prices for printable packs that were configured for non-default infill levels.

We fetch prices for a printable pack with one item via https://www.treatstock.com/api/v2/printable-pack-costs?printablePackId=407177&location[country]=US

We then proceed to set the infill to 100 via PUT https://www.treatstock.com/api/v2/printable-packs/407177 with the payload
```javascript
{
	"modelTextureInfo": {
		"isOneMaterialForKit": "0",
		"modelTexture": null,
		"partsMaterial": {
			"MP:3416673": {
				"color": "White",
				"materialGroup": "PLA",
				"infill": 100,
				"material": null
			}
		}
	}
}
```
If we then check the prices again via https://www.treatstock.com/api/v2/printable-pack-costs?printablePackId=407177&location[country]=US the prices for PLA White did not change at all.

We would expect the `GET /printable-pack-costs` response to have different prices for a given modelTexture, if the printable pack has been configured with a higher infill.
Alternatively it could always include a list of infill prices for a given vendor / material combination.

**Comment by analytic83** [comment]
Hi, do you test it? Working fine now?

**Comment by alex-all3dp** [comment]
Hello,
I tested again and at first glance it seems to work fine now. Thank you! :)
