### ISSUE TITLE
Price request returns only one result for each materialGroup and color combination

### ISSUE THREAD

**Issue by henry-all3dp** [ceo-treatstock/apiv2#9]
After creating a printable pack the subsequent price request will return a list of prices for each `materialGroup` and `color`. While this is a quick solution to get the cheapest price for all available materials at once it would make sense to have a list of prices for each `materialGroup` and `color` when querying that combination directly (as in the treatstock web application).

So, while
`GET` - `http://www.treatstock.com/api/v2/printable-pack-costs?private-key=<apiKey>&printablePackId=<printablePackId>&location%5Bcountry%5D=US`
can be used to return a **list of single prices** for each `materialGroup` and `color` combination, it would make sense to have
`GET` - `http://www.treatstock.com/api/v2/printable-pack-costs?private-key=<apiKey>&printablePackId=<printablePackId>&location%5Bcountry%5D=US&printerMaterialGroup=<materialGroup>&printerColor=<color>`
to return a **list of prices from different printers**, e.g.:

```
[
  {
    "printablePackId": 12345,
    "materialGroup": "PLA",
    "printer": "Maker Select V2",
    "providerId": 0,
    "rating": 5,
    "reviewsCount": 162,
    "color": "White",
    "price": 4.99,
    "deliveryPrice": 5.27,
    "url": "https://www.treatstock.com/model3d/preload-printable-pack?packPublicToken=token&printerMaterialGroupId=16&printerColorId=90"
  },
  {
    "printablePackId": 67890,
    "materialGroup": "PLA",
    "printer": "Maker Select V1",
    "providerId": 1,
    "rating": 5,
    "reviewsCount": 162,
    "color": "White",
    "price": 5.99,
    "deliveryPrice": 5.27,
    "url": "https://www.treatstock.com/model3d/preload-printable-pack?packPublicToken=token&printerMaterialGroupId=16&printerColorId=90"
  },
  ...
]
```

The third potential request, i.e. providing just a `materialGroup` **or** a `color`, could also return a list of single prices for each existing `materialGroup` and `color` combination similar to the general non-specific price request.

With this solution it would be possible to have a fallback when the first, i.e. cheapest,  provider in a price list is not able to print the printable pack in the subsequent order request and the next provider in the list is known and therefore selectable.

Let me know your thoughts!

**Comment by analytic83** [comment]
Hi, to get  **list of prices from different printers**:  you should user other request.
Use expample: https://github.com/Treatstock/apiv2/blob/master/examples/06_PlaceOrderColored.php
Request: GetPrintablePackOffersRequest

The third potential request, you can create by filtering /api/v2/printable-pack-costs on your side.

**Comment by henry-all3dp** [comment]
Hello @analitic1983,
many thanks for your response.

I attempted to use the GetPrintablePackOffersRequest, but was not able to receive any prices because of the following error I receive:
```
{
  "name": "TypeError",
  "message": "Argument 1 passed to common\\models\\factories\\LocationFactory::createFromGeoLocation() must be an instance of common\\models\\GeoLocation, null given, called in /var/www/treatstock/common/modules/api/v2/controllers/PrintablePackOffersController.php on line 108",
  "code": 0
}
```

Do you know why this is the case? All other price requests accept a `location[country]` parameter, but this one seems to be ignored.

The alternative (i.e. filtering the printable pack costs) does not work because of the reasons in the ticket: It only contains prices for each material and colour combination once.

**Comment by analytic83** [comment]
You need set location for printable pack.
> $createRequest->locationCountryIso = 'US'; // Optional params: to get printable pack price info

**Comment by henry-all3dp** [comment]
@analitic1983 Is there a specific reason why for the `GetPrintablePackOffersRequest` it is required to have the printable pack be created with location (the later update of a location for a printable pack is not working), especially since the `GetPrintablePackPricesRequest` accepts the location. Having the location as a parameter of the `GetPrintablePackOffersRequest` would omit the need to re-upload the model (or several models) when switching the location and reduce the number of upload requests.

**Comment by henry-all3dp** [comment]
@analitic1983 any update on this issue?

**Comment by ceo-treatstock** [comment]
@henry-all3dp Sorry for the late reply. We will plan the task for developers of the availability of changing the location in the request 'ChangePrintablePackRequest'.

**Comment by ceo-treatstock** [comment]
@henry-all3dp We have some updates here. Now you don't have to re-upload files to change location. Please use 
'ChangePrintablePack' request 
We added location parameter there.
https://github.com/Treatstock/apiv2/commit/e9a3d2a86fa07750778490112dc82416005e23e6
